controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    # TODO: I must write this to suit the bicycle. It must contain the topic cmd_vel
    # bi_cont:
    #   type: diff_drive_controller/DiffDriveController

    # like joint_state_publisher for robot_state_publisher to work
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster
